-- Name of the Day: auto vs user-edited picks (single table)

ALTER TABLE public.mail_name_of_day_picks
  ADD COLUMN IF NOT EXISTS pick_source text,
  ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT timezone('utc'::text, now());

UPDATE public.mail_name_of_day_picks SET pick_source = 'auto' WHERE pick_source IS NULL;

ALTER TABLE public.mail_name_of_day_picks
  ALTER COLUMN pick_source SET DEFAULT 'auto',
  ALTER COLUMN pick_source SET NOT NULL;

ALTER TABLE public.mail_name_of_day_picks DROP CONSTRAINT IF EXISTS mail_name_of_day_picks_pick_source_check;
ALTER TABLE public.mail_name_of_day_picks ADD CONSTRAINT mail_name_of_day_picks_pick_source_check
  CHECK (pick_source IN ('auto', 'user_edited'));

COMMENT ON COLUMN public.mail_name_of_day_picks.pick_source IS 'auto = generated by mail-name-of-day; user_edited = staff override (automation will not overwrite)';
COMMENT ON COLUMN public.mail_name_of_day_picks.updated_at IS 'Last insert or update';
